### PR TITLE
Issue32

### PR DESCRIPTION
**Pull request by isaakwheeler**
adding events page and attaching it to the navigation.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Looks good to me

**Comment by ghost** [comment]
Not sure how to change my "approve" but I believe you want to use android:src and not tools:src In your fragment_events.xml file to get the image to show up on the app.  I downloaded your code and used android:src="@drawable/img"to verify that I was able to see that image on your card in the emulator.  Without that change to your code, the card does not show an image to me. 
Per https://stackoverflow.com/questions/39753804/differences-androidsrc-and-toolssrc

**Review by haythamodeh — APPROVED** [review]
Looks good.

**Review by ghost — APPROVED** [review]
Looks goos

**Review by odjuliarso — APPROVED** [review]
runs great

**Pull request merged**
